// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mottu.Infrastructure.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Mottu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250909022554_UpdateCreate")]
    partial class UpdateCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mottu.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("MOTOS", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.HasKey("Id");

                    b.ToTable("PATIOS", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.UsuarioPatio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("USUARIOS_PATIO", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Moto", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mottu.Domain.ValueObjects.Placa", "Placa", b1 =>
                        {
                            b1.Property<int>("MotoId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("NVARCHAR2(7)")
                                .HasColumnName("PLACA");

                            b1.HasKey("MotoId");

                            b1.ToTable("MOTOS");

                            b1.WithOwner()
                                .HasForeignKey("MotoId");
                        });

                    b.OwnsOne("Mottu.Domain.ValueObjects.SetorCor", "SetorCor", b1 =>
                        {
                            b1.Property<int>("MotoId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<string>("Cor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("NVARCHAR2(20)")
                                .HasColumnName("COR");

                            b1.Property<string>("Setor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("NVARCHAR2(20)")
                                .HasColumnName("SETOR");

                            b1.HasKey("MotoId");

                            b1.ToTable("MOTOS");

                            b1.WithOwner()
                                .HasForeignKey("MotoId");
                        });

                    b.Navigation("Patio");

                    b.Navigation("Placa")
                        .IsRequired();

                    b.Navigation("SetorCor")
                        .IsRequired();
                });

            modelBuilder.Entity("Mottu.Domain.Entities.UsuarioPatio", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
